### ISSUE TITLE
Just make it return a string or bool

### ISSUE THREAD

**Issue by tsak** [martincarlin87/image-sorter#3]
https://github.com/martincarlin87/image-sorter/blob/ddb4c00d4e549b38d9fbf03d1614d74ea8396006/imagesorter.go#L15

I think it would be better to have this just take the `request` and return a string or bool instead of writing into a buffer passed as a buffer. Much cleaner and easier to reason about.

```go
func ImageSorterSubmit(request *http.Request) string {
    // ...
    return "success"
}

**Comment by martincarlin87** [comment]
good idea, will take a look at that.
